// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaDoacaoSangue.Models;

public partial class Agendamento
{
    public int Id { get; set; }

    public int DoadorId { get; set; }

    public int HemocentroId { get; set; }

    public DateTime Data { get; set; }

    public TimeSpan Hora { get; set; }

    public string Status { get; set; }

    public DateTime? CriadoEm { get; set; }

    public DateTime? AtualizadoEm { get; set; }

    public string Obs { get; set; }

    public virtual Doadore Doador { get; set; }

    public virtual Hemocentro Hemocentro { get; set; }
}