// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaDoacaoSangue.Models;

public partial class Doadore
{
    public int Id { get; set; }

    public int UsuarioId { get; set; }

    public string NomeCompleto { get; set; }

    public DateTime DataNascimento { get; set; }

    public string TipoSanguineo { get; set; }

    public string Sexo { get; set; }

    public string Endereco { get; set; }

    public string Telefone { get; set; }

    public DateTime? DataUltimaDoacao { get; set; }

    public string Cpf { get; set; }

    public decimal Peso { get; set; }

    public virtual Usuario Usuario { get; set; }
}