// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaDoacaoSangue.Models;

public partial class Hemocentro
{
    public int Id { get; set; }

    public int UsuarioId { get; set; }

    public string NomeHemocentro { get; set; }

    public string Endereco { get; set; }

    public string Telefone { get; set; }

    public string EmailContato { get; set; }

    public string Cnpj { get; set; }

    public virtual Usuario Usuario { get; set; }
}