// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaDoacaoSangue.Models;

public partial class Usuario
{
    public int Id { get; set; }

    public string Username { get; set; }

    public string SenhaHash { get; set; }

    public string Email { get; set; }

    public string TipoUsuario { get; set; }

    public DateTime? CriadoEm { get; set; }

    public DateTime? AtualizadoEm { get; set; }

    public virtual ICollection<Doadore> Doadores { get; set; } = new List<Doadore>();

    public virtual ICollection<Hemocentro> Hemocentros { get; set; } = new List<Hemocentro>();
}